apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-pvc
  namespace: tortuga
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: seedbox-slow-mirror
  resources:
    requests:
      storage: 10Gi
