$ANSIBLE_VAULT;1.1;AES256
63313462633765353766323638656638643031316637666137663066653061393534643738643839
3132636534616139383035613731653234356234326635390a393834656139633461316233333736
64383635633436613063313731396532663763613830336238396436656432623636666638353030
6538356331343463380a306237356337326433383731363932353931313833323136633663383165
62626535373665663630316532343763653637393336346461393633363461386165306237313330
37376435393138313636663530613365643339663866353439343738363437666130353964616561
36626436396266376137366634323636323334643864626539646237616235666134616262663237
39623766353635316438346637623330633861313161626239363134613261623036373130626135
39613631646362666132373466643434353232663832386363333265366435613966356564363836
33393730623132346539393330363730656664396433653461336265663334386535366266313332
646262656339656361666633306332613962
