$ANSIBLE_VAULT;1.1;AES256
66303736313333663261663762393737646538386133656132313037616465663433386465386334
3835333464343137356132633431333765303331626431340a613732636236323231383961396266
37383431363335346432303737383335393361656639363838366461386435393566386462653731
3736343162356333360a383139626139653265393530396238623361353264383261376237643962
35613738653433336637653138396364323235323362356164633665306531653837663030373537
38323130663139303537303066623064313831393965623736383665386131623065356230346236
62643736646238643036306139303935666361616166356161333565616639306438626163356539
38646432363664393939386431663532366464353566346430323562616434346665313636663235
62353361333861326234313132323630643836613764326437383839636433323765653163303539
34323132323731346233383162333933623839656234353134346637353030636338373930653066
323764353262306363656364376435373130
