apiVersion: v1
kind: Secret
metadata:
    name: tailscale-operator-values
    namespace: tailscale
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:FVGpLfX8xa/fd2DCmd5+H/3t0HfA7dYs7Jnr2Kc7g2u1GJvrYyYBABa0ldacCpbhpgmBAn5umTjjv5vWT54PGAnexd2YhBxxhTNNb/IJp8Iix84WnGMIbj54XC78kg/Zk6WW9UFOlAg7xRNimrpik/OlzNk+6xRYNQ==,iv:qcsoK6ck/c4F6TG3MIYvgLjIgFte0+rBG+Ughq0s2VM=,tag:Wo8/ld/SS7QKXRmCLsK9FQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age105qzkfymzzt63ytzmfkcw0k5g82cewepnuz4plcgqy9n9hwz5yqs7k3ku5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQ1hKcUtBTmcvWW93bU1k
            QnVSdnZDM282RE5MeHR1U0pMYlF5dHRKcVFVCnBNNHFxT1VWalh0VlBHaXc4ZnZW
            Um9HNWhDOHRFdGpKM1JNbXFpU2h0MWMKLS0tIGFSZERQYnRvYjBtMEhhbmQvc3ZC
            bFhnRG5KZkkrT1V1YmM5cUkrMHVqanMKO6LUjfVHuLVtgg6LX900Q8WPUTe/Jcu7
            YKhxd+JT3g2n1WPl33/gRlVXd/njbK2uke+ZUxbFL0Jw+NAHwqRVyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T18:13:53Z"
    mac: ENC[AES256_GCM,data:6Ez9YLwKS62/2+HNOxh8Z84vz8vh2RgSr/Boin4zakmzTsNtPu/ClbmytbfyHOxdNUEC8wOpOys+s6tCpNMF+yUTdl8xODjzqGJwbyRDB3Mq9RH89tMNzs+eXFRw2+0pFckBBbD0Zqxju6XDmmnsr2IIGXtvY7ukNqoeR0gbvYc=,iv:oBvuJBRh+tCNnSSlM79PqueJO099g5pTlQqWRPwzDXk=,tag:eM67dZUGoTkboxAPffOjrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
