---
ansible_python_interpreter: /usr/bin/python3
ansible_user: mrled

ansible_become_method: sudo
ansible_become_user: root
ansible_become_pass: "{{ lookup('pipe', 'op item get j2zvpoyo5j7eukwfb3pz45j64i --fields password') }}"

http_backchannel_dnsname: naragua.backchannel.younix.us
http_backchannel_aws_access_key_id: "{{ vault_http_backchannel_aws_access_key_id }}"
http_backchannel_aws_secret_access_key: "{{ vault_http_backchannel_aws_secret_access_key }}"
http_backchannel_subdomain_ports:
  micahrl: 64224
  lrhacim: 42246
