$ANSIBLE_VAULT;1.1;AES256
35353738623662373864313262343139616161653466616533336333623234373434383134663263
3165363266326262363363633634373332353166616161350a396333323662333138633537646635
35376433626138663764663761623034373235656136343230303662326435613737303363653638
6430666262343466610a316263643763383035366166633832353137396138323338636561666461
65646534636561633437623761666131313630653036333631653930656130333463313934633965
63326136663463376562323539633139386236396636663061373938383032613637383239363062
63613765336262643736636436323866353830316635656338313638343862326537306238633662
39333538353336666330323465646437616638396133663036343838363039643763373031323334
31663932396631343830616464383465323533656638343031336337613365313231326235373139
30653137303433363833316232613638633765363933363564653162393939316331663030343939
62333234636430313565363863353565393766323063386636623037326364366330366239346264
32323966323264303435
