$ANSIBLE_VAULT;1.1;AES256
38396262623764396338663865346539363031393831643133636362316530653139663936363137
3836303439343665303730393261636631626335656136320a666339613465316133373632303561
30343937663936633236343032323933343735383365353266663438333536363035623366303030
6433376365646439640a373964366362336664393533313835663539373236653066393364373936
37316634373538326639656130393935373464323663646139346136663338356164306264353332
37313031663738643930643838643964623138383137656365653039623733613635633866636438
66666535323131643330363163323936313365333862663838616232373032663137366462626465
31643237303936316331353762306365653730366366303463356332646530643033343638343131
65303031336135633661303866646466636235343631313166303962323332383736306366353630
32343264613139353264643731316563623765356436356430653366333532643861326561396433
66323363393230396362643866306463333938653235663464363161363438376165623635383832
30633535323765613931
