$ANSIBLE_VAULT;1.1;AES256
38303834666162653234643164353133313637313637366462353730626566306334303930356262
6431366338613139303334626330623064353237356464660a396364306334313364623761623466
34666566396137643364306237346561306632613764333463333533353634306131376166386536
6564323263313631610a356631636561666662363062373835643461306261393265656565323365
32623132646337656538343430353137363465363666306564666662373933653639316138373463
31616232323939356539323462303835306361613435643132346138303161313530376164656462
62333663306239373533316638363031613939303564653133643739353363306661646538353331
66373561313465663133343734323164633631666266323465356231656161656565343361393739
65616663656664623032653830626565353764353330343362313835373761326566356639653363
36343163373330623634313431656563613437366636313163653835313862323665626335353562
35303235643330303939363335323537313533636434393830343966363964396235343332633735
61656638323032343133
