---
- name: restart traefik
  command: launchctl bootout system/us.younix.backchannel && launchctl bootstrap system /Library/LaunchDaemons/us.younix.backchannel.plist
  become: yes
  ignore_errors: yes
