---

- name: Deploy pprox
  hosts: pprox
  roles:
    - { name: autoupgrade, tags: ["autoupgrade"] }
    - { name: emailfwd, tags: ["emailfwd"] }
    - { name: tailscale, tags: ["tailscale"] }
    - { name: pprox, tags: ["pprox"] }
