apiVersion: v1
kind: ConfigMap
metadata:
  name: bk2-ytdl-options
  namespace: tortuga

data:

  ## WARNING: Reminder to be careful of ${var...} here (and everywhere), which is interpreted by Flux Kustomize. Escape with $${var...}.

  options.yaml: |+
    proxy: http://pprox.tortuga.svc.cluster.local:3128
