apiVersion: v1
kind: Secret
metadata:
    name: seedboxk8s-config
    namespace: flux-system
type: Opaque
stringData:
    testingClusterFqdn: ENC[AES256_GCM,data:5uXZ/P/e4i7H,iv:wkt8OGq9H0lt/9/HY8fYIiQKStxbgyOyUUkUfz8KdNo=,tag:p5u+G4gcE0lYuolAvts0VQ==,type:str]
    testingClusterFqdnHostedZoneId: ENC[AES256_GCM,data:gdwJD95ug1yl997XU1SGZjGN0TmX,iv:PisdFmQNpw6dDf73YLuwZp2AUu89qCPw5QiXPFKZvzY=,tag:JIQ7oFpqGF4Fz4NEHMepwA==,type:str]
    productionClusterFqdn: ENC[AES256_GCM,data:/vPt7cwmuS3DThivtltg,iv:6S6rj6Pkf17ViQcxNRCRbC+1/YkhFiGbmjJ5rqG38AA=,tag:VrmlXVugAX2kLzFVmuwjcg==,type:str]
    productionClusterFqdnHostedZoneId: ENC[AES256_GCM,data:kEqht1Kj7UUAUHXFBeJ5aUOrZwfj,iv:f8CEs9X3E2PLXv64oZh7AxnXtDovBRH1fwugcSmXtRI=,tag:Qq8+Qkjv3ay/MUxd26WnLg==,type:str]
    x3Image: ENC[AES256_GCM,data:2UlKXJLvo8WDAED0gEtJ4ENX+Qcd,iv:msy6Yv5BZmtC52yx6id4kMHsMMk6bo32C9CghkcEpvc=,tag:x/mwBsN3NqXc2V2gZdup9g==,type:str]
    shhhImage: ENC[AES256_GCM,data:5An4Os1SFJUaIsFmwjt2VFw=,iv:PST4QCc7IA+3IP5+nRSJXBfMXhFM2owmsi+iy4BQSM4=,tag:JQQTXFqNIGshKlvWJ2kqog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age105qzkfymzzt63ytzmfkcw0k5g82cewepnuz4plcgqy9n9hwz5yqs7k3ku5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRnFTVWNvR0FFZGRhM2RU
            ZDZLY0s5SzJnd1U0RjlQTmduTjJLUGVzV2hRClIvVGZYRWdsR3dqRkwzUWJKZVdq
            M05xcFlocjBSUmppclRJVmVKLzZQdW8KLS0tIEQrUjdzNGJhemYwbzFlVkozR0cy
            RGZ4SzBtaUtFQkJlUGF6d1dVbEU2RzgK2EtNwYfnup2bom7ViqFBxJD4OGcBU8Rc
            bGNdXSNr4HjMfDe/CzD7KBup7bRIIkE8itAO5/fY/xG5+ELJgQf6JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T02:06:58Z"
    mac: ENC[AES256_GCM,data:cJ7ODeSpZP553nlMrfRVSqpGxXflMRt6uI093Rzs6oFFrw0UH32nt3o8R4N0zBpfSNqRLwUgUsPZo67C7AIZgxFKH56zSSX+SC46FWbKFDdaka0xqp7fvYM0fyRc/rhTsOZTNbh4+2pl3m7hwCyrdO49Hc2Ynz5QZg9ZJ+Ntiy4=,iv:zxd60oLHs7t+XpgXqxg6SJRvf1oDk3m8Ehy1i5u0cGw=,tag:OR8J8Lt/Lbh2bSL0it+IVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
