apiVersion: v1
kind: Secret
metadata:
    name: seedboxk8s-config
    namespace: flux-system
type: Opaque
stringData:
    testingClusterFqdn: ENC[AES256_GCM,data:TlFyTldcH0Jd,iv:GWZfHxF2akUHbOMZY6Q8ojhJ1/IQk2SeOXRy259RQww=,tag:PtaSEyFe/hJHPjjOiL2q/g==,type:str]
    testingClusterFqdnHostedZoneId: ENC[AES256_GCM,data:gWhStYvVXgy+H2AtNfToRqaIYCXp,iv:VrWBU9HYoyHJ4j+FLT38iOgoYDtQmuldPfv4vIXyb8w=,tag:n229ZtL9pNJvBuI6k+xyxg==,type:str]
    productionClusterFqdn: ENC[AES256_GCM,data:g6vr+e1dztWNrTZ1SaaR,iv:VMRWmIzOHAFYEQaNo3AnKLuI+7pUu0awQfoz+RONpuI=,tag:QpUsYu2Oo9xpXPWIme603g==,type:str]
    productionClusterFqdnHostedZoneId: ENC[AES256_GCM,data:aH+uIM+WMGINirvECz1oZ3j8Omx3,iv:hDjej+b2UDubsWmU+ewnb3omECP+qxfdjsko61jE7GM=,tag:YF+7vQoQc4GejrF32eQrWA==,type:str]
    x3Image: ENC[AES256_GCM,data:+8BXVzd1AZ+t+oXm/MrZQvVo13uK,iv:Do2o8JInEPJg3S2GOT8mlsfebLHOQBhbOeLGVPZt8Zg=,tag:H4TUSQM16s/OOcRWOWFO3w==,type:str]
    shhhImage: ENC[AES256_GCM,data:yRhxkZ4rZnSCgT6wpTE6Q9pAJOuxjpp7Iw==,iv:nK8DUJbxlDOWqQCX9RbhsXbQCC5hnbqX5qmf4TFty2Q=,tag:JCxbhbTbTO+hS9w+Xd1Ojg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age105qzkfymzzt63ytzmfkcw0k5g82cewepnuz4plcgqy9n9hwz5yqs7k3ku5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRTEzNEp6dUNEdk5TTTkr
            Uld6NTY1cHRKMlFQSUQxWklkMW52VWV2NWw0Cng2cGR6UHpoQ1g2SXFHWTNGaFZu
            YVBPRDdGOXRvU3k1L1VFeUplNE1JWTQKLS0tIDU0S0pONFplNjlVaDV0WW9mbHpa
            OHBuUlI5RVZyTkFkRTJjdjJBZFlQYzAKyi6e+5hgjhz6XDt6IkK0rKtuS6N7gz6w
            u9x/iUDUiAY4DApVz6m+mSH/iH+14bg0yBpTo402ihLcAGK3Ifl/KA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T02:58:02Z"
    mac: ENC[AES256_GCM,data:oHRLirROBujcXvOMz5mp4jQwdGj02rWt897wn1g6sPXNUP2IijnxIwu7w2xLkUnFdSpELVyCOAGTmfBzg5WwOH/TJI41vqVJsJwVkTR+5Tp9R05jOM1SyURIQSgdTRM29NZHQH2yf6eqRnUWigBr+wNy0TCZTXEz6LiZKg5B5Wk=,iv:J0/x/Cy8FsmDQ7d3WsaIoesEVjVhU1npqGLPHfE6ApQ=,tag:ud3gHzpJz76T1TbdzRDIkw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
