apiVersion: v1
kind: Secret
metadata:
    name: seedboxk8s-config
    namespace: flux-system
type: Opaque
stringData:
    testingClusterFqdn: ENC[AES256_GCM,data:X6pBm4zOPD31,iv:staAPK/2AG7kA8RWE3UVPAt7HHT8TMaJx3klkubXdWY=,tag:F4oDja3eGpRvC3LQSk4Pqg==,type:str]
    testingClusterFqdnHostedZoneId: ENC[AES256_GCM,data:x8Ai8E+T+8JgOTKyuE8+9OVCDtYX,iv:+TA5AMVetbB5sY+xOnHg467JxSEw84BskUq3ioxZZlM=,tag:WnlQoad1VpKJbRhadXaY3A==,type:str]
    productionClusterFqdn: ENC[AES256_GCM,data:f47cPNqfYMQ4febYL6n5,iv:bEIO5cxKr6T4aASSk1k9BHQzQj3gocNIdZD4ZwgkiiY=,tag:96qzgCMbQGjmXSH3Sio2tw==,type:str]
    productionClusterFqdnHostedZoneId: ENC[AES256_GCM,data:7/9WfgFrUkrQKfg+g9ERcMg+QPlU,iv:MfACpQ4d5N9W0jQ8b75IzksrIhImQHgmKsvKYtftm8s=,tag:tQDkzpUjEk95gRRGs29enA==,type:str]
    x3Image: ENC[AES256_GCM,data:rfUovsiG9XdIlhRtuzA=,iv:20UHo+sCIseYiG5A2fn1EykLlfRGVEa6IsQl8+yFcII=,tag:CBq6YbK5NITZlyjmI1d+lA==,type:str]
    shhhImage: ENC[AES256_GCM,data:AwCP5xXeFyTi4UMvAcLpmO8M7tYkHw==,iv:Qqf6GldjKjvUcgm1rPInxnLCWFTlsEQ6vOaTwNTuid0=,tag:ou/ZACCZ2gNjFGg/Lel2/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age105qzkfymzzt63ytzmfkcw0k5g82cewepnuz4plcgqy9n9hwz5yqs7k3ku5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUHExR2dzSmtLMVBETjBQ
            UzZjU3dyWC9YNjFKTXdPbmRmWnZUMzZWRUIwCkZUVjE4OVFLRlYzTE5KeFB6aDBD
            eStQTmFLVStsQ1JFRXN6SVdtd1ZFOU0KLS0tIDZ1Q0VKNkdKOUJhTzkydkovZmQw
            ak9UdWlzeHQ5MjM1UnR1amxGOHdvMG8K5Z7+MFPvSjFaAGcRasrYgg8RQRRCL/P1
            eGucEtBZaQ467trBIz2pF4nloTeTTZ0B9fkmVvkaepR3nnHUsC60Jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T13:08:09Z"
    mac: ENC[AES256_GCM,data:DEJs5XoqRGP6TuAgI/RM0VNuGPdM3yf3hYYkDTL/FynIhYQw77VIxc7geap7TH96jGKRVOat2V2nP1ai3GR7axb/8EiT3bPNxuyzVqo7j+BFrMKIg7SHOoyf4n8x6WkA7EmPj5f56/9toL6EUDZcJN0pPw02sHO9D9Ly5WteFVM=,iv:RRYTwOtzXdfRpOWgf0sx8ETmY/GuvCBrVymkrHmuADg=,tag:5xXjJHzuSzUy6xVDkwA1qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
