apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pinepods
  namespace: pinepods
  annotations:
    kubernetes.io/ingress.class: traefik-tailscale
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pinepods.${productionClusterFqdn}`)
      kind: Rule
      services:
        - name: pinepods
          kind: Service
          port: 8040
      middlewares:
        - name: bridgetroll-mw
          namespace: bridgetroll
  tls:
    secretName: seedbox-wildcard-backing-secret
