apiVersion: v1
kind: Secret
metadata:
    name: pinepods-secret-values
    namespace: pinepods
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:LHq1SQ0VEeAuOXVGNS4QlnaRPalNUi/O1Znqm73hTBuewMAF+mAw9fSA5tuAcyC8suVCX8/X2GY8VoyxKAMnWsUNsrz7wPVTlFmhFilM3QjBzUTC0THC00khfcP8VYiUdeYUb6x0i7rjo8w2TY/8BsUFvf3IhgGFpyk=,iv:SqnZfsZjlXnQd4rI5Zz1LmmFDl0PheO/83XV9XDJROI=,tag:8Fc4NrbAKNPPoeYpJL2p7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age105qzkfymzzt63ytzmfkcw0k5g82cewepnuz4plcgqy9n9hwz5yqs7k3ku5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VGR4dFRrUWFzbktRbCs1
            aWR0a2FENVNjMUhlL3JQTE85YmNwVlg3WTJNCkpBZGJXd21GeFlLNmplNGxaQXhX
            V3BxMmRWQ0ovTkRUS2dGWDhMS1RnUG8KLS0tIEFaR3F6cGdXK3NUMVNycERGV1Nq
            cmVQb210dWJMMklZMEszS0RQazdoenMKS3OmufOUnoCVK7oG1LIJsaHMG6NfZ/yx
            4f3ZwXYmaZKb/umA0dT/ZuyRorGdvtAhoUAWAGinJ30kAauOQU3aiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T13:02:00Z"
    mac: ENC[AES256_GCM,data:QsaEFauwjODKxQcgPMEOpS0MsD2SGgoA8F7he/K7CMeeSLXYS1xeFgiJugFHOm6gAK6fjqe2OKHx7d+UBq+az9lvGBUnX4uMKBaxaAj8gy5v2OkMAxfn7mihJhX6WJ+8ml8ccqYLlEgjKXDwR0SAFEcGU9XeFbTi1Xe+BI8bD/M=,iv:ly+r3qAWL5qkXXSg/nIFrNq4gyrWFSoYdw9i7JEkB4E=,tag:PtASM0fXly/l1cV+bZ4pag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
