apiVersion: v1
kind: Secret
metadata:
    name: pinepods-secret-values
    namespace: pinepods
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:cNrvoxF0eWPWCUNoW0a8rKTTCA+aBXExyBQH2xDgzf2l1gicu2k/qXTTrcjTlhSrUhmxT3ndkj+dp998jf7NbSdI82J58pqIkXvCI09+8TjF1z5DHwqcAxQ4FitJ92gjiLwiju9u/i6LgNem5E/5clmtKtrZ+3TzoIIBFjF0WizjK9KZHnLXu7vv8k3yA9BmOfRifc24Ugp8zE70cAjHkrt+2ZKAuJbB6KgVHw==,iv:GnyAGb/4Motwmfhn8IIYW0HOh9Dt63CSGELk4Ep9lO4=,tag:Ls/Em7PY4/BKcNuPgIOAwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age105qzkfymzzt63ytzmfkcw0k5g82cewepnuz4plcgqy9n9hwz5yqs7k3ku5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZEl5VVdMWjdRM0lCKzhN
            N1EvOGxhelp2eWRsREdiVlJ0UGRROTQzMkV3CnJNVzN0cjhRaVVhUHd1N1RtSGF4
            bWM3czkyL0Z5bGtCa0pFQXNMSXNoeEUKLS0tIHlkOGw0bjlKYUFsdDd6bEpKMzJn
            aHc4ZmpEOThlS2IzbnR3ZUliUVg5SnMKwhTI4sQzFju5UA/iDiEIug6jl0n6P5kD
            BqdZEKf8qaw1fIW12Do3YbT+BqjecNz/230AcbF+NecJz/OjcuiRgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T13:23:52Z"
    mac: ENC[AES256_GCM,data:Fy67SUZfsT2Sgdw+U6a4diPDah8jOuO0hztLR9NRZ/VoiWkxt49mN209wpDQFbu9RBWnGQeNu405PjxMWg7k/wuu193rBOrmkSc8lE7Aa7NpA1aEElUftumKi8BRQV1QvNm08ixV1w8fzV62tDQ4dchnX+AYn9iN2o+x2Ef5bJ4=,iv:WrQn0LRIHbkrm1SqVW+lb4z2gzpzfn315fzJ1Rlfnzs=,tag:/mD1fUWU0nzKJl99GyBRiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
