apiVersion: v1
kind: Secret
metadata:
    name: pinepods-secret-values
    namespace: pinepods
type: Opaque
stringData:
    values.yaml: |
        externalDatabase:
          password: "Heegai7lu7uiGh4oolaech4rohgh9Soh"

        env:
          PASSWORD: "ahTuxoobaisohzeis1ieHutephaikoof"
          DB_PASSWORD: "Heegai7lu7uiGh4oolaech4rohgh9Soh"
          VALKEY_PASSWORD: "eeK8aish7eiquaqu9tohqu5zo6eeweiM"
