apiVersion: v1
kind: Secret
metadata:
    name: pinepods-secret-values
    # or whatever namespace you deploy pinepods into
    namespace: media
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:GkFFNzMsFQxMKC/JP4sg+DntoXwYhObzb/4riHwX5NJ8Hx3cbeMFcGaK4OJrFbVw1Q35rruZB12jrSuHqs+iJ3QIRF+260aJ2JcEU1TlrBc6PnzbZelOOq+1jLBhwnkn13YZYozty7WLITTE8dAbhOzkkYKBMr+rlIU=,iv:4vP2p9xrEC6S/p2uk3tuiv+2Fu1UrTewXT6/cpLH/qA=,tag:iDjOWpiKDB1DLvUm1EmEmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age105qzkfymzzt63ytzmfkcw0k5g82cewepnuz4plcgqy9n9hwz5yqs7k3ku5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVk9aNXRtQUJ5VFZLVDRm
            eG5iaXFnemVXUTROOGN3TG15OVkyUWFwZ3lBCkhiNXFSUzlTUjFQTnE3MnRJeTZE
            eWlOaHZ4NjVXU1BNUHR3Yk1lRlBtVmsKLS0tIE1WcEhNZnNFZWNjVVhsNVRSdXdD
            UEZDbHQ0b2F1dzNISldBdG5SM3QxcnMK0u+jAHTizg/yS7WYbG/Zgjcyj2X+eIvs
            hSCqRRu/1x4fHIc9atKuV8f+zRmQdEN6WYglmvw0An6wv3c0kk5Xsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T12:56:19Z"
    mac: ENC[AES256_GCM,data:lcFs3vlGdz9Cc1bTVQT575eCb2uOkZ5QqBQ2CgbyKVVZD23TDBg33snCC5e0O31DD3SRbH8oa4z1mWdZqyjtuDkbZxzwDwtTk9j+hFVvlawHjSpIWJ+4/sTpF5nuZK+QEBYnfkrpk22Wp36PLrvG1egDY398EWNeJYkfmThgbM4=,iv:6yWoYnZfXFEs3tAWe/AVmXI00q3wf2doHSxjq1gt8lE=,tag:usggiOyWmclRxwHIj+1vWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
